# Generated by Django 2.2.17 on 2020-12-10 20:16

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import hrapp.models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок вопроса')),
                ('content', tinymce.models.HTMLField(verbose_name='Текст вопроса')),
                ('answers', djongo.models.fields.ArrayField(model_container=hrapp.models.Answer, model_form_class=hrapp.models.AnswerForm)),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('user_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('results', djongo.models.fields.ArrayField(model_container=hrapp.models.Result, model_form_class=hrapp.models.ResultForm)),
            ],
            options={
                'verbose_name': 'Итоги тестирования',
                'verbose_name_plural': 'Итоги тестирования',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название опросника')),
                ('questions', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Question')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросник',
            },
        ),
    ]
