# Generated by Django 2.2.17 on 2020-12-11 06:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок вопроса'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название опросника'),
        ),
    ]
