# Generated by Django 2.2.17 on 2020-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_auto_20201211_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='user_id',
        ),
        migrations.AddField(
            model_name='testing',
            name='username',
            field=models.CharField(default='', editable=False, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
