version: '3.7'
services:
#  flask:
#   build: .
#   container_name: e7_in_docker
#   image: digitalocean.com/flask-python
#   restart: unless-stopped
#   environment:
#    - PORT=5000
#    - REDIS_HOST=redis
#    - REDIS_PORT=6379
#    - DB_NAME=db_mongo
#   command: gunicorn -w 4 -b 0.0.0.0:5000 api:app
#   ports:
#     - 5000:5000
#   depends_on:
#     - redis
#     - mongo
#   links:
#     - mongo

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    command: mongod
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
       - 27017:27017
volumes:
  mongodbdata:
    driver: local